[tool.poetry]
name = "streamlit-ollama-chat"
version = "0.1.0"
description = "A simple Streamlit chat interface for Ollama"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
streamlit = "^1.28.0"
requests = "^2.31.0"
llama-stack-client = "^0.2.13"
fire = "^0.7.0"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 